services:
  go-migrate:
    build:
      context: ./migrator
      dockerfile: Dockerfile.dev
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal_net


  postgres:
    build:
      context: ./postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    networks:
      - internal_net
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: 
      context: ./backend/main
      dockerfile: Dockerfile.dev
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: unless-stopped
    volumes:
      - ./backend/main:/app
    networks:
      - internal_net
    depends_on:
      - postgres
      - go-migrate

  uta-processor:
    build: 
      context: ./backend/uta-processor
      dockerfile: Dockerfile.dev
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: unless-stopped
    volumes:
      - ./backend/uta-processor:/app
    networks:
      - internal_net
    depends_on:
      - postgres
      - go-migrate

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    restart: unless-stopped
    networks:
      - internal_net



  nginx:
    build: ./nginx
    depends_on:
      - backend
      - frontend
      - uta-processor
    ports:
      - "80:80"
    networks:
      - internal_net


  notification-svc:
    build: 
      context: ./notification-svc
      dockerfile: Dockerfile.dev
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./notification-svc:/app
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - internal_net

    

volumes:
  postgres_storage:

networks:
  internal_net:
    internal: false # true
