services:
  go-migrate:
    build:
      context: ./migrator
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    build:
      context: ./postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: 
      context: ./backend/main
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "8080"
    restart: unless-stopped
    depends_on:
      - go-migrate

  uta-processor:
    build: 
      context: ./backend/uta-processor
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "8080"
    restart: unless-stopped
    depends_on:
      - postgres

  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000"
    restart: unless-stopped

  nginx:
    build: ./nginx
    depends_on:
      - backend
      - frontend
      - uta-processor
    ports:
      - "80:80"

volumes:
  postgres_storage:
