services:
  go-migrate:
    build:
      context: ./migrator
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal_net
    restart: on-failure

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    networks:
      - internal_net
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}' ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend/main
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    networks:
      - internal_net
    volumes:
      - secrets:/secrets:ro
    depends_on:
      postgres:
        condition: service_healthy
      go-migrate:
        condition: service_started
      security-svc:
        condition: service_completed_successfully

  uta-processor:
    build:
      context: ./backend/uta-processor
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    networks:
      - internal_net
    depends_on:
      postgres:
        condition: service_healthy
      go-migrate:
        condition: service_started
      security-svc:
        condition: service_completed_successfully


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    networks:
      - internal_net

  nginx:
    build: ./nginx
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - certbot_etc:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    depends_on:
      - backend
      - frontend
      - uta-processor
      - certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - external_net
      - internal_net
    restart: always

  notification-svc:
    build:
      context: ./notification-svc
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      go-migrate:
        condition: service_started
      security-svc:
        condition: service_completed_successfully

    networks:
      - internal_net
  certbot:
    build:
      context: ./certbot
      dockerfile: Dockerfile
    volumes:
      - certbot_etc:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    environment:
      LETSENCRYPT_STAGING: ${LETSENCRYPT_STAGING}
      DOMAIN_NAME: ${DOMAIN_NAME}
    networks:
      - external_net
    restart: always

  security-svc:
    build:
      context: ./security-svc
      dockerfile: Dockerfile
    volumes:
      - secrets:/secrets:rw

volumes:
  postgres_storage:
  certbot_etc:
  certbot_www:
  secrets:

networks:
  internal_net:
    internal: true
  external_net:
    internal: false
